### PR TITLE
Fixing dialog for restore account.

### PR DESCRIPTION
**Pull request by avipatel91**
Fixing bug for https://github.com/AdExBlockchain/adex-dapp/issues/1

### CODE REVIEW

**Comment by IvoPaunov** [comment]
Thanks for the fix I can merge it like that but the right way is to set translation string at ([adex-translation](https://github.com/AdExBlockchain/adex-translations)) in en-US.json e.g. "SIGNIN_CREATE_ACCOUNT": "Create account".
Then use this.propst("SIGNIN_CREATE_ACCOUN") in the react component. Note that in order to have this.props.t (transations) for any component you have to wrap it with 'Translate HOC'
```
...
import Translate from 'components/translate/Translate'
...
class Signin extends Component ...
...
title={this.state.method === 'create' ? this.propst('SIGNIN_CREATE_ACCOUN' : this.propst('RESTOR_CREATE_ACCOUN'}
...
export default connect(
  mapStateToProps,
  mapDispatchToProps
)(Translate(Signin))
```
I'll appreciate the 'translation way'

**Comment by avipatel91** [comment]
Thanks for the feedback! Does the latest commit abide by standards?

**Comment by avipatel91** [comment]
Also, I will need to change where adex-translation in package.json. I can wait for [this PR](https://github.com/AdExBlockchain/adex-translations/pull/1) to get merged and then point to the latest commit. Or I can just point it to the master branch. Up to you.

**Comment by IvoPaunov** [comment]
([The translations PR](https://github.com/AdExBlockchain/adex-translations/commit/b13ed25839159f93aeb0b6fea27a4c75cef155e3)) is merged. Change the package and I'll merge. 
Thank you

**Pull request merged**
